---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-FTPServer
no_index:
  directory:
    - t
    - inc
requires:
  BSD::Resource: 0
  Carp: 0
  DynaLoader: 0
  Fcntl: 0
  Getopt::Long: 0
  IO::Dir: 0
  IO::File: 0
  IO::Handle: 0
  IO::Scalar: 1.126
  IO::Seekable: 0
  IO::Select: 0
  IO::Socket: 0
  IPC::Open2: 0
  POSIX: 0
  Socket: 0
  Sys::Hostname: 0
  Sys::Syslog: 0
  Test::More: 0
version: 1.124
